### ISSUE TITLE
Cancer sample tracking

### ISSUE THREAD

**Issue by jessieno** [NationalGenomicsInfrastructure/charon#47]
Hej! It would be great if we could also include a field for cancer samples in the database. 

I would like this because the first IGN project from UU-SNP will be comprised mostly of cancer samples. In some cases the genotype-sequencing concordance from cancer samples will not be >99%. This can be because of loss or gains of large regions of the genome that can affect the genotype calls differently between the two data types. Thus, for cancer samples we will not require the 99% concordance for a sample to pass final QC.

**Comment by Galithil** [comment]
Samples have a "type" field that will be used in this case.
